services:
  - type: web
    name: laravel-on-render
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: /usr/bin/supervisord -c /etc/supervisord.conf
    plan: free
    ports:
      - port: 80
        protocol: http
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d15tbi7diees73efvmb0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: commercial
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: zeP0CRvACJERd9FnqVQ3VIcP2r6xEgJN
